import { useState } from 'react';
import { ArrowDown, ArrowDownRight, ArrowUp, ChevronDown, ChevronUp, Download, Info, SlidersHorizontal, Sparkles, Users } from 'lucide-react';
import type { Dataset, Model } from '../lib/data';
import { isStale, providerInfo } from '../lib/data';
import { comparisonCsv, downloadFile, eligibilityReason, exactDate, inputBandLabel, isBestCost, money, normalizeWorkload, offeringLabel, rankOfferings, tokens, type Workload } from '../lib/pricing';
import { ModelMark, ProviderMark, SourceLink } from './UI';
import { History } from './History';
import { RecentMovements } from './Changes';

type SortKey = 'input' | 'output' | 'workload';
export function Compare({ data, model, onModel, tier, onTier, workload, onWorkload, onChanges, onMethodology }: { data: Dataset; model: Model; onModel: (id: string) => void; tier: string; onTier: (tier: string) => void; workload: Workload; onWorkload: (workload: Workload) => void; onChanges: () => void; onMethodology: () => void }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  const [sort, setSort] = useState<SortKey>('workload');
  const [direction, setDirection] = useState(1);
  const ranked = rankOfferings(data, model.id, workload, tier);
  const eligible = ranked.filter((row) => row.cost.eligible);
  const best = eligible[0];
  const cheapestInput = [...eligible].sort((a, b) => a.price.input_per_million - b.price.input_per_million)[0];
  const cheapestOutput = [...eligible].sort((a, b) => a.price.output_per_million - b.price.output_per_million)[0];
  const providerCount = new Set(ranked.map((row) => row.offering.provider)).size;
  const highestInput = Math.max(0, ...eligible.map((r) => r.price.input_per_million));
  const highestEstimate = Math.max(0, ...eligible.map((r) => r.cost.perRequest));
  const savings = best && highestEstimate > 0 ? Math.round((1 - best.cost.perRequest / highestEstimate) * 100) : 0;
  const rows = [...ranked].sort((a, b) => Number(b.cost.eligible) - Number(a.cost.eligible) || direction * ((sort === 'input' ? a.price.input_per_million : sort === 'output' ? a.price.output_per_million : a.cost.perRequest) - (sort === 'input' ? b.price.input_per_million : sort === 'output' ? b.price.output_per_million : b.cost.perRequest)) || a.offering.id.localeCompare(b.offering.id));
  const update = (key: keyof Workload, value: number) => onWorkload(normalizeWorkload({ ...workload, [key]: value }));
  const sortButton = (key: SortKey, label: string) => <button className="table-sort" onClick={() => { setSort(key); setDirection(sort === key ? -direction : 1); }} aria-label={`Sort by ${label}${sort === key && direction === 1 ? ', descending' : ', ascending'}`}>{label}{sort === key ? direction === 1 ? <ArrowDown size={12} /> : <ArrowUp size={12} /> : <ChevronDown size={11} />}</button>;
  return <>
    <div className="page-heading"><div className="eyebrow"><span className="eyebrow-line" /> LESS GUESSWORK. MORE VISIBILITY.</div><h1>Same model. <span>Different price.</span></h1><p>Compare what providers charge, understand the differences, and follow prices over time.</p></div>
    <section className="model-selector-panel"><ModelMark model={model} /><div className="model-selection"><label htmlFor="model-selector">SELECT A MODEL</label><select id="model-selector" value={model.id} onChange={(e) => onModel(e.target.value)}>{data.models.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><div className="model-meta"><span>{model.creator}</span><span className="meta-dot">·</span><span>{model.version}</span><span className={model.open_weight ? 'open-weight-badge' : 'closed-weight-badge'}>{model.open_weight ? 'Open weights' : 'Proprietary'}</span>{model.lifecycle === 'legacy' && <span className="legacy-badge">Legacy release</span>}</div>{!model.open_weight && <p className="model-description">{model.description}{model.documentation_url && <> <a href={model.documentation_url} target="_blank" rel="noopener noreferrer">Model reference ↗</a></>}</p>}</div><div className="model-selection-note"><span className="live-dot" /> {providerCount} providers compared<small>Same canonical model. Visible variants.</small></div></section>
    <div className="stat-grid">
      <div className="stat-card"><div className="stat-label">LOWEST INPUT <ArrowDownRight size={16} /></div><div className="stat-value">{cheapestInput ? money(cheapestInput.price.input_per_million) : '—'}<span>/ 1M tokens</span></div><div className="stat-description"><span className="provider-dot" style={{ background: cheapestInput ? providerInfo(cheapestInput.offering.provider).color : undefined }} />{cheapestInput ? providerInfo(cheapestInput.offering.provider).name : 'No published offering'}</div></div>
      <div className="stat-card"><div className="stat-label">LOWEST OUTPUT <ArrowDownRight size={16} /></div><div className="stat-value">{cheapestOutput ? money(cheapestOutput.price.output_per_million) : '—'}<span>/ 1M tokens</span></div><div className="stat-description"><span className="provider-dot" style={{ background: cheapestOutput ? providerInfo(cheapestOutput.offering.provider).color : undefined }} />{cheapestOutput ? providerInfo(cheapestOutput.offering.provider).name : 'No published offering'}</div></div>
      <div className="stat-card accent"><div className="stat-label">YOUR WORKLOAD <Sparkles size={15} /></div><div className={`stat-value${best && money(best.cost.total).length > 8 ? ' wide-total' : ''}`}>{best ? money(best.cost.total) : '—'}<span>estimated total</span></div><div className="stat-description">{best ? <><span className="savings-pill">{savings}% less</span><span>than the highest estimate</span></> : 'No offering fits the published token limits'}</div></div>
      <div className="stat-card"><div className="stat-label">PROVIDERS TRACKED <Users size={15} /></div><div className="stat-value">{providerCount}<span>{ranked.length} distinct offerings</span></div><div className="stat-description">{cheapestInput && cheapestInput.price.input_per_million > 0 ? <><strong>{(highestInput / cheapestInput.price.input_per_million).toFixed(1)}×</strong> input price spread</> : 'Official, observed list prices'}</div></div>
    </div>
    <section className="panel workload-panel" aria-labelledby="workload-title"><div className="workload-heading"><span className="section-icon"><SlidersHorizontal size={18} /></span><div><h2 id="workload-title">Your workload</h2><p>A fair comparison starts with your token mix.</p></div><span className="subtle-badge">Analysis only</span></div>
      <div className="workload-grid"><label className="numeric-field">Input tokens <span>per request</span><div><input aria-label="Input tokens per request" type="number" min="0" max="1000000000" step="100" value={workload.inputTokens} onChange={(e) => update('inputTokens', Number(e.target.value))} /><span>tokens</span></div></label><label className="numeric-field">Output tokens <span>per request</span><div><input aria-label="Output tokens per request" type="number" min="0" max="1000000000" step="100" value={workload.outputTokens} onChange={(e) => update('outputTokens', Number(e.target.value))} /><span>tokens</span></div></label><label className="numeric-field">Number of requests <span>in your workload</span><div><input aria-label="Number of requests" type="number" min="0" max="1000000000" step="1000" value={workload.requests} onChange={(e) => update('requests', Number(e.target.value))} /><span>requests</span></div></label><label className="cache-field">Cache hit rate <span>{workload.cacheHitPercent}%</span><input aria-label="Cache hit rate" type="range" min="0" max="100" value={workload.cacheHitPercent} onChange={(e) => update('cacheHitPercent', Number(e.target.value))} style={{ '--range-progress': `${workload.cacheHitPercent}%` } as React.CSSProperties} /><small>Share of input tokens already cached</small></label></div>
    </section>
    <section className="panel comparison-panel"><div className="section-heading"><div><h2>Provider comparison <span className="count-badge">{ranked.length}</span></h2><p>USD per 1 million tokens. Ranked for your workload and applicable prompt band.</p></div><div className="table-actions"><select aria-label="Service tier" value={tier} onChange={(e) => onTier(e.target.value)}><option value="standard">Standard tier</option><option value="priority">Priority tier</option><option value="flex">Flex tier</option><option value="all">All tiers</option></select><button className="icon-button" aria-label="Export comparison as CSV" title="Export comparison as CSV" disabled={!ranked.length} onClick={() => downloadFile(comparisonCsv(ranked, workload), `${model.id.split('/').pop()}-comparison.csv`)}><Download size={17} /></button></div></div>
      {ranked.length ? <div className="table-scroll"><table className="comparison-table"><thead><tr><th>Provider</th><th aria-sort={sort === 'input' ? direction === 1 ? 'ascending' : 'descending' : undefined}>{sortButton('input', 'Input')}</th><th aria-sort={sort === 'output' ? direction === 1 ? 'ascending' : 'descending' : undefined}>{sortButton('output', 'Output')}</th><th>Cache read</th><th>Cache write</th><th>Context</th><th>Variant / tier</th><th aria-sort={sort === 'workload' ? direction === 1 ? 'ascending' : 'descending' : undefined}>{sortButton('workload', 'Workload cost')}</th><th><span className="sr-only">Sources and details</span></th></tr></thead><tbody>{rows.map((row) => {
        const { offering: o, price: p, cost: c } = row;
        const bestCost = isBestCost(row, best);
        const failed = data.status.providers.find((s) => s.id === o.provider)?.state === 'error';
        return <CompareRow key={o.id} row={row} bestCost={bestCost} lowestInput={p.input_per_million === cheapestInput?.price.input_per_million} failed={failed} expanded={expanded === o.id} onExpand={() => setExpanded(expanded === o.id ? null : o.id)} />;
      })}</tbody></table></div> : <div className="empty-state"><SlidersHorizontal size={28} /><h3>No tracked offerings in this tier</h3><p>Choose Standard or All tiers to see published prices for this model.</p></div>}
      <div className="table-note"><Info size={14} /><span>Prompt bands count all input, including cached tokens. Cache-write, storage and tool fees are excluded. Unknown context limits remain unverified.</span><button onClick={onMethodology}>Details</button></div>
    </section>
    <div className="insights-grid"><History data={data} model={model} tier={tier} /><RecentMovements data={data} onAll={onChanges} /></div>
    <div className="bottom-note"><Info size={15} /><p>A lower price is not a promise of equivalent performance. Compare precision, context, and service tier before deciding.</p><button onClick={onMethodology}>Our methodology <ChevronDown size={14} /></button></div>
  </>;
}

function CompareRow({ row, bestCost, lowestInput, failed, expanded, onExpand }: { row: ReturnType<typeof rankOfferings>[number]; bestCost: boolean; lowestInput: boolean; failed?: boolean; expanded: boolean; onExpand: () => void }) {
  const { offering: o, price: p, cost: c } = row;
  const info = providerInfo(o.provider);
  const stale = isStale(p.observed_at);
  return <><tr className={`${bestCost ? 'best-row' : ''} ${!c.eligible ? 'limited-row' : ''}`} data-testid="offering-row"><td><div className="provider-cell"><ProviderMark provider={o.provider} /><div><strong>{info.name}</strong><div className="provider-subtitle">{bestCost ? <span className="lowest-badge">Lowest estimate</span> : o.service_tier === 'standard' ? ['vertex', 'bedrock', 'azure'].includes(o.provider) ? 'Managed cloud API' : 'Inference API' : `${o.service_tier} service`}{(failed || stale) && <span className="stale-badge" title={failed ? 'Collection failed. Showing the last successful observation.' : 'This price was observed more than 48 hours ago.'}>{failed ? 'Last known' : 'Stale'}</span>}</div></div></div></td>
    <td className={`price-cell ${lowestInput ? 'lowest-price' : ''}`}>{money(p.input_per_million)}</td><td className="price-cell">{money(p.output_per_million)}</td><td className="price-cell">{p.cache_read_per_million === null ? <span className="not-published" title="No published cache read rate">—</span> : money(p.cache_read_per_million)}</td><td className="price-cell">{p.cache_write_per_million === null ? <span className="not-published" title="No published cache write rate">—</span> : money(p.cache_write_per_million)}</td><td title={o.context_window === null ? 'Not published; context fit cannot be verified' : `${o.context_window.toLocaleString('en-US')} tokens`}>{tokens(o.context_window)}{!c.fitsContext && <small className="context-warning">Too small</small>}</td><td><span className="variant-badge">{offeringLabel(o)}</span><small className="tier-label">{o.service_tier} · {o.region}</small>{inputBandLabel(o) && <small className={`input-band ${!c.fitsInputRange ? 'context-warning' : ''}`} title={`Input tokens: ${o.min_input_tokens ?? 0} to ${o.max_input_tokens ?? 'unbounded by this price band'}`}>{inputBandLabel(o)}</small>}</td><td className={`estimate-cell ${bestCost ? 'lowest-price' : ''}`}>{c.eligible ? <><strong>{money(c.total)}</strong><small>{money(c.perRequest, true)} / request{c.cacheFallback ? ' *' : ''}{c.contextUnverified ? ' †' : ''}</small><small>{money(c.perMillionRequests)} / 1M requests</small></> : <><strong>—</strong><small>{eligibilityReason(c)}</small></>}</td><td><div className="row-actions"><SourceLink url={p.source_url} label={`Official pricing source for ${info.name}`} /><button className="icon-button" onClick={onExpand} aria-expanded={expanded} aria-label={`Details for ${info.name} ${o.variant} ${o.service_tier}`} title={`Observed ${exactDate(p.observed_at)}`}>{expanded ? <ChevronUp size={15} /> : <ChevronDown size={15} />}</button></div></td></tr>
    {expanded && <tr className="offering-details"><td colSpan={9}><div className="offering-detail-grid"><div><span>PROVIDER MODEL ID</span><code>{o.provider_model_id}</code></div><div><span>OBSERVED AT</span><time dateTime={p.observed_at}>{exactDate(p.observed_at)}</time></div><div><span>RESPONSE SHA-256</span><code title={p.source_sha256}>{p.source_sha256.slice(0, 20)}…</code></div><div><span>SOURCE</span><a href={p.source_url} target="_blank" rel="noopener noreferrer">{new URL(p.source_url).hostname} ↗</a></div></div>{o.pricing_notes && <p className="pricing-notes">{o.pricing_notes}</p>}{o.max_output_tokens != null && <p className="pricing-notes">Published output limit: {o.max_output_tokens.toLocaleString('en-US')} tokens per request.</p>}{(c.cacheFallback || c.contextUnverified) && <div className="detail-caveat">{c.cacheFallback && <span>* No published cache read price; regular input price applied.</span>}{c.contextUnverified && <span>† Context window is unpublished; verify workload fit with the provider.</span>}</div>}</td></tr>}
  </>;
}
