import { ArrowUpRight, Check, Database, Download, FileCheck2, GitBranch, Info, ShieldCheck } from 'lucide-react';
import type { Dataset } from '../lib/data';
import { isStale } from '../lib/data';
import { dateLabel, downloadFile, exactDate } from '../lib/pricing';
import { ProviderMark } from './UI';

export function Methodology({ data }: { data: Dataset }) {
  return <><div className="page-heading"><div className="eyebrow">SMALL. TRANSPARENT. AUDITABLE.</div><h1>Know what’s behind <span>the numbers.</span></h1><p>This is an observation project—not a router, a benchmark, or a recommendation engine.</p></div>
    <div className="method-grid"><section className="panel method-card"><span className="method-icon"><ShieldCheck size={23} /></span><h2>Official sources first</h2><p>Public provider APIs and official model/pricing documentation. Every price has its source URL, observation time, and response hash. Reviewed direct-provider comparisons do not substitute gateway prices. Provider pages expose source-native catalogs, including gateway routes, credits, compute billing, and unreviewed document evidence. They do not automatically become comparisons.</p></section><section className="panel method-card"><span className="method-icon"><GitBranch size={23} /></span><h2>History, never rewritten</h2><p>Daily source checks; history records first observations and price changes, including intraday changes. Unchanged checks update freshness without duplicating price history. Historical CSV rows are append-only; JSON is a derived dashboard cache. Git adds a second audit trail.</p></section><section className="panel method-card"><span className="method-icon"><FileCheck2 size={23} /></span><h2>Same model ≠ same offering</h2><p>Manually reviewed, exact aliases link models. Precision, context, region, service tier, prompt-length pricing bands, and Turbo variants remain separate. Unknown values stay unknown, not guessed.</p></section></div>
    <section className="panel collector-panel"><div className="section-heading"><div><h2>Collector health <span className="count-badge">{data.status.providers.length}</span></h2><p>Last run: {exactDate(data.status.last_run_at)} · daily schedule: 06:17 UTC</p></div><span className="subtle-badge">No visitor API keys required</span></div><div className="table-scroll"><table className="collector-table"><thead><tr><th>Official provider</th><th>Status</th><th>Last successful observation</th><th>Offerings</th><th>Availability coverage</th><th>Source</th></tr></thead><tbody>{data.status.providers.map((p) => <tr key={p.id}><td><div className="provider-cell"><ProviderMark provider={p.id} /><strong>{p.name}</strong></div></td><td><span className={`health-badge ${p.state === 'error' || p.coverage_state === 'limited' || isStale(p.last_success_at) ? 'warning' : ''}`}><span className="live-dot" />{p.state === 'error' ? 'Failed · retained' : isStale(p.last_success_at) ? 'Stale' : p.coverage_state === 'limited' ? 'Limited source' : 'Healthy'}</span></td><td title={p.last_success_at ? exactDate(p.last_success_at) : ''}>{p.last_success_at ? dateLabel(p.last_success_at, true) : 'Never succeeded'}{p.error && <small className="collector-error">{p.error}</small>}{p.coverage_state === 'limited' && p.fallback_reason && <small className="collector-error">{p.fallback_reason}</small>}</td><td>{p.offering_count}</td><td><span className="subtle-badge">{p.collection_scope === 'inventory_only' ? 'Inventory only' : p.authoritative_catalog ? 'Full catalog' : 'Priced listings only'}</span></td><td><a className="text-link" href={p.source_url} target="_blank" rel="noopener noreferrer">Official source <ArrowUpRight size={14} /></a></td></tr>)}</tbody></table></div><div className="table-note"><Info size={15} /><span>Failed collectors preserve their last good observations. Delistings are detected only from a successfully parsed full catalog, never from a failed request or a partial pricing page.</span></div></section>
    <div className="method-details-grid"><section className="panel calculator-method"><h2>The workload calculation</h2><p>Input tokens are the total input, including the cached portion.</p><div className="formula"><code>uncached = input × (1 − cache hit %)</code><code>cached = input × cache hit %</code><code>cost = (uncached × input rate<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + cached × cache read rate<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + output × output rate) / 1,000,000</code></div><ul className="check-list"><li><Check size={15} />No double counting of cached input.</li><li><Check size={15} />Unknown cache read rates fall back to regular input prices.</li><li><Check size={15} />Cache-write charges are displayed (5-minute TTL for Claude), but not modeled. Cache storage per token-hour and tool/grounding fees are also excluded: this assumes already-populated caches.</li><li><Check size={15} />Only matching prompt-length price bands are eligible, using all input including cached tokens. Known context/output limits are enforced; unknown limits remain explicitly unverified.</li><li><Check size={15} />Only USD public list prices. No credits, commitments, negotiated pricing, tax, or other fees.</li></ul></section><section className="panel dataset-card"><span className="method-icon"><Database size={23} /></span><h2>The dataset is the experiment.</h2><p>Tracking started {data.status.first_observed_at ? dateLabel(data.status.first_observed_at) : 'with the first collection'}. There is no invented historical backfill. First-seen events describe our discovery date, not when a provider launched the model.</p><div className="dataset-stats"><div><strong>{data.status.observation_count}</strong><span>observations</span></div><div><strong>{data.changes.filter((c) => c.kind === 'price_changed').length}</strong><span>verified price changes</span></div></div><button className="button primary" onClick={() => downloadFile(JSON.stringify(data, null, 2), 'tokentokentoken-dataset.json', 'application/json')}><Download size={16} /> Download reviewed dataset</button><a className="text-link history-download" href={`${import.meta.env.BASE_URL}price_history.csv`} download="tokentokentoken-price-history.csv">Download append-only history CSV <ArrowUpRight size={14} /></a><p className="dataset-disclaimer">This export contains reviewed comparison data. Native records can be exported from provider pages. Collection timestamps show when we fetched a source, not a guarantee of instantaneous billing prices. Verify the official page before making a decision.</p></section></div>
  </>;
}
